
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button btnFactura;
	private global::Gtk.Button btnLimpiar;
	private global::Gtk.Label lblProducto1;
	private global::Gtk.Label lblProducto2;
	private global::Gtk.Label lblProducto3;
	private global::Gtk.Label lblSubtotal;
	private global::Gtk.Entry Producto1;
	private global::Gtk.Entry Producto2;
	private global::Gtk.Entry Producto3;
	private global::Gtk.Entry Subtotal;
	private global::Gtk.Entry IVA;
	private global::Gtk.Entry Total;
	private global::Gtk.Label lblTotal;
	private global::Gtk.Label lblIVA;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnFactura = new global::Gtk.Button ();
		this.btnFactura.CanFocus = true;
		this.btnFactura.Name = "btnFactura";
		this.btnFactura.UseUnderline = true;
		this.btnFactura.Label = global::Mono.Unix.Catalog.GetString ("FACTURA");
		this.fixed1.Add (this.btnFactura);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnFactura]));
		w1.X = 85;
		w1.Y = 221;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnLimpiar = new global::Gtk.Button ();
		this.btnLimpiar.CanFocus = true;
		this.btnLimpiar.Name = "btnLimpiar";
		this.btnLimpiar.UseUnderline = true;
		this.btnLimpiar.Label = global::Mono.Unix.Catalog.GetString ("LIMPIAR");
		this.fixed1.Add (this.btnLimpiar);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnLimpiar]));
		w2.X = 196;
		w2.Y = 221;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblProducto1 = new global::Gtk.Label ();
		this.lblProducto1.Name = "lblProducto1";
		this.lblProducto1.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 1");
		this.fixed1.Add (this.lblProducto1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblProducto1]));
		w3.X = 56;
		w3.Y = 19;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblProducto2 = new global::Gtk.Label ();
		this.lblProducto2.Name = "lblProducto2";
		this.lblProducto2.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 2");
		this.fixed1.Add (this.lblProducto2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblProducto2]));
		w4.X = 54;
		w4.Y = 44;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblProducto3 = new global::Gtk.Label ();
		this.lblProducto3.Name = "lblProducto3";
		this.lblProducto3.LabelProp = global::Mono.Unix.Catalog.GetString ("Producto 3");
		this.fixed1.Add (this.lblProducto3);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblProducto3]));
		w5.X = 54;
		w5.Y = 68;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblSubtotal = new global::Gtk.Label ();
		this.lblSubtotal.Name = "lblSubtotal";
		this.lblSubtotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Subtotal");
		this.fixed1.Add (this.lblSubtotal);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblSubtotal]));
		w6.X = 34;
		w6.Y = 112;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Producto1 = new global::Gtk.Entry ();
		this.Producto1.CanFocus = true;
		this.Producto1.Name = "Producto1";
		this.Producto1.IsEditable = true;
		this.Producto1.InvisibleChar = '●';
		this.fixed1.Add (this.Producto1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Producto1]));
		w7.X = 129;
		w7.Y = 12;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Producto2 = new global::Gtk.Entry ();
		this.Producto2.CanFocus = true;
		this.Producto2.Name = "Producto2";
		this.Producto2.IsEditable = true;
		this.Producto2.InvisibleChar = '●';
		this.fixed1.Add (this.Producto2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Producto2]));
		w8.X = 129;
		w8.Y = 39;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Producto3 = new global::Gtk.Entry ();
		this.Producto3.CanFocus = true;
		this.Producto3.Name = "Producto3";
		this.Producto3.IsEditable = true;
		this.Producto3.InvisibleChar = '●';
		this.fixed1.Add (this.Producto3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Producto3]));
		w9.X = 129;
		w9.Y = 68;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Subtotal = new global::Gtk.Entry ();
		this.Subtotal.CanFocus = true;
		this.Subtotal.Name = "Subtotal";
		this.Subtotal.IsEditable = true;
		this.Subtotal.InvisibleChar = '●';
		this.fixed1.Add (this.Subtotal);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Subtotal]));
		w10.X = 88;
		w10.Y = 106;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.IVA = new global::Gtk.Entry ();
		this.IVA.CanFocus = true;
		this.IVA.Name = "IVA";
		this.IVA.IsEditable = true;
		this.IVA.InvisibleChar = '●';
		this.fixed1.Add (this.IVA);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.IVA]));
		w11.X = 87;
		w11.Y = 132;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Total = new global::Gtk.Entry ();
		this.Total.CanFocus = true;
		this.Total.Name = "Total";
		this.Total.IsEditable = true;
		this.Total.InvisibleChar = '●';
		this.fixed1.Add (this.Total);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Total]));
		w12.X = 87;
		w12.Y = 160;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblTotal = new global::Gtk.Label ();
		this.lblTotal.Name = "lblTotal";
		this.lblTotal.LabelProp = global::Mono.Unix.Catalog.GetString ("Total");
		this.fixed1.Add (this.lblTotal);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblTotal]));
		w13.X = 49;
		w13.Y = 163;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblIVA = new global::Gtk.Label ();
		this.lblIVA.Name = "lblIVA";
		this.lblIVA.LabelProp = global::Mono.Unix.Catalog.GetString ("IVA");
		this.fixed1.Add (this.lblIVA);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblIVA]));
		w14.X = 54;
		w14.Y = 137;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnFactura.Clicked += new global::System.EventHandler (this.OnBtnFacturaClicked);
		this.btnLimpiar.Clicked += new global::System.EventHandler (this.OnBtnLimpiarClicked);
	}
}
